theme: minima
skin: dark
title: Move to Mastodon for Urbanists
url: https://philam.github.io/movetomastodon
disqus: 
    shortname: disqus_98KPqC6bAD
minima:
  social_links:
    github: philam
    flickr: philipmallis
    mastodon:
     - username: philip
       instance: aus.social
