theme: minima
title: Move to Mastodon for urban planning, cities and transport
header_pages:
  - index.md
  - list.md
  social_links:
    github: philam
    flickr: philipmallis
    mastodon:
     - username: philip
       instance: aus.social
