theme: minima
skin: dark
title: Move to Mastodon for Urbanists
description: Urban planning, cities and transport on Mastodon
url: https://philam.github.io/movetomastodon
disqus: 
    shortname: https-philam-github-io-movetomastodon
minima:
  social_links:
    github: philam
    flickr: philipmallis
    mastodon:
     - username: philip
       instance: aus.social
